# https://docs.docker.com/compose/compose-file
# docker-compose up
# docker-compose stop
# docker-compose down
version: '3'

networks:
  shared-network:
    driver: bridge

services:

  # Start of the Postgresql
  mongo:
    container_name: postgres
    networks:
      - shared-network
    image: postgres
    ports:
      - 5432:5432
    command: --bind_ip 0.0.0.0

  # Start of the blog service
  sales-api:
    container_name: blog
    networks:
      - shared-network
    image: blog:1.0
    ports:
      - 3123:3123
    volumes:
      - ${PWD}/private.pem:/app/private.pem

  # This sidecar publishes metrics to the console by default.
  metrics:
    container_name: metrics
    networks:
      - shared-network
    image: metrics-amd64:1.0
    ports:
      - 3001:3001 # EXPVAR API
      - 4001:4001 # DEBUG API

  jaeger-collector:
      image: jaegertracing/jaeger-collector
      command: ["--cassandra.keyspace=jaeger_v1_dc1", "--cassandra.servers=cassandra", "--collector.zipkin.http-port=9411"]
      ports:
        - "14269"
        - "14268:14268"
        - "14267"
        - "14250"
        - "9411:9411"
      restart: on-failure
      depends_on:
        - cassandra-schema

    jaeger-query:
      image: jaegertracing/jaeger-query
      command: ["--cassandra.keyspace=jaeger_v1_dc1", "--cassandra.servers=cassandra"]
      ports:
        - "16686:16686"
        - "16687"
      restart: on-failure
      depends_on:
        - cassandra-schema

    jaeger-agent:
      image: jaegertracing/jaeger-agent
      command: ["--reporter.type=grpc", "--reporter.grpc.host-port=jaeger-collector:14250"]
      ports:
        - "5775:5775/udp"
        - "6831:6831/udp"
        - "6832:6832/udp"
        - "5778:5778"
      restart: on-failure
      depends_on:
        - jaeger-collector